
server:
    port: 8089

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springlearn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: hs3921
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: create
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
            show-sql: true